# Generated by Django 2.0.3 on 2018-04-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_ip', models.GenericIPAddressField()),
                ('switch_username', models.CharField(max_length=50)),
                ('switch_password', models.CharField(max_length=128)),
                ('switch_type', models.IntegerField(choices=[(1, 'CiscoIOS'), (2, 'CiscoNx'), (3, 'Huawei'), (4, 'H3C'), (5, 'Juniper Junos')])),
            ],
        ),
    ]
